version: "3.7"

services: 
    database_boardme:
        image: postgres
        container_name: database_boardme
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=boardme
            - POSTGRES_DB=boardme
        volumes: 
            - pgdata:/data/postgres
    app:
        build: .
        container_name: boardme
        ports: 
        - 3333:3333
        volumes: 
        - .:/usr/project
        links: 
            - database_boardme
        depends_on: 
            - database_boardme 
volumes: 
    pgdata:
        driver: local